added hashing method to store the hashed passwords
annu12340/Choose-Smart pull request #5
Opened 2020-10-01 08:41 UTC by kavya1229

Hi annu,

I have made the changes to hash the passwords before storing it in db and while logging in i am comparing the entered password and corresponding db password and printing the output as true or false, for your reference.

I have changed one print statement from print session['user'] to print(session['user'])

I have changed the import statement in main.py as shown below, as the previous one causes error in python3

#from urllib2 import Request, urlopen as uReq as syntax got changed in python3
from urllib.request import urlopen as uReq

I hope I have made the changes correctly, Please let me know if I did anything wrong as this is my first time contributing to the open-source project

2020-10-02 05:06 UTC, annu12340 requested changes

2020-10-02 05:06 UTC, annu12340 commented on Main.py
> +        data = User.query.filter_by(email=email).first()
Hey here we need to check for both the email and password of the user (**password** is missing)

2020-10-03 08:11 UTC, annu12340 commented
Pls resolve the conflicts

2020-10-03 13:34 UTC, kavya1229 commented
created a new pull request

2020-10-03 13:34 UTC, closed without merging