Hacktober 2020
annu12340/Choose-Smart pull request #8
Opened 2020-10-02 12:33 UTC by navya252001

I have made changes which I felt are enough. I would be happy to hear your suggestions :)

2020-10-02 12:57 UTC, annu12340 commented
Pls resolve the conflicts

2020-10-02 13:01 UTC, annu12340 requested changes

2020-10-02 13:01 UTC, annu12340 commented on README.md
> +## Usage
Change **usage** to **Demo** (or **screenshots**)

2020-10-02 13:01 UTC, annu12340 commented on README.md
> +    <a href="https://github.com/annu12340/Choose-Smart"><strong>Explore the docs »</strong></a>
We don't require this line (This link is just redundant)

2020-10-02 13:01 UTC, annu12340 commented on README.md
> +
Pls add the screenshots here (instead of keeping it at the bottom)

2020-10-02 13:01 UTC, annu12340 commented on README.md
> +## Roadmap
I think the roadmaps is not required

2020-10-03 06:51 UTC, navya252001 commented
Sir please help me in HACKTOBER FEST 2020
We will honor all valid pull requests prior to this change, and as of October 3, 2020 at 12:00:00 UTC – and October 3 in all time zones – pull requests will only count toward earning a T-shirt or planting a tree if they are submitted in a repository classified with the ‘hacktoberfest’ topic. The pull requests will also need to be merged, approved by a maintainer, or labeled as ‘hacktoberfest-accepted’ in order to qualify. The deadline for completions, merging, labeling, and approving is November 1.
Latest guidelines issued by the organizers
I sincerely hope you will help me
I have already submitted a pull request
https://hacktoberfest.digitalocean.com/hacktoberfest-update
I am attaching the link too for your convenience

2020-10-03 07:50 UTC, annu12340 requested changes

2020-10-03 07:50 UTC, annu12340 commented on README.md
>  ### Prerequisites
Change Prerequisites to installation
and remove the title ** installation** from line 73

2020-10-03 07:52 UTC, annu12340 commented
Pls resolve the conflicts and then I would merge the pr :)

2020-10-03 07:54 UTC, navya252001 commented
Done

2020-10-03 07:57 UTC, annu12340 commented
> Done

Still, the files are showing conflicts
Kindly resolve them

2020-10-03 08:09 UTC, merged

2020-10-03 08:09 UTC, annu12340 commented
Thank you @navya252001 for the pr 😄

2020-10-03 08:09 UTC, navya252001 commented
thankyou for the opportunity

2020-10-03 09:00 UTC, navya252001 commented
Ma'am please make the changes according to these guidelines for making my PR count
We will honor all valid pull requests prior to this change, and as of October 3, 2020 at 12:00:00 UTC – and October 3 in all time zones – pull requests will only count toward earning a T-shirt or planting a tree if they are submitted in a repository classified with the ‘hacktoberfest’ topic. The pull requests will also need to be merged, approved by a maintainer, or labeled as ‘hacktoberfest-accepted’ in order to qualify. The deadline for completions, merging, labeling, and approving is November 1.

2020-10-03 09:03 UTC, navya252001 commented
Label your repository with hacktoberfest
My PR as hacktoberfest-accepted
PLEASE DO IT ASAP

2020-10-03 09:03 UTC, navya252001 commented
Ok its cool I just saw your issue is hacktober marked

2020-10-03 09:06 UTC, annu12340 commented
> Ok its cool I just saw your issue is hacktober marked

Everything is sorted now, right?
Any changes required from my side?

2020-10-03 09:09 UTC, navya252001 commented
Yes thanku